spring.application.name=task-manager-api
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Keep colored logs in the console
spring.output.ansi.enabled=ALWAYS

# Reduce noise while preserving application logs
logging.level.root=WARN
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.kiernan.finance_tracker_api=INFO

# Concise, colorized output
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%-35logger{36}){cyan} %clr(-){faint} %msg%n



# Optional: disable Spring banner
spring.main.banner-mode=off